spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none

  jackson:
    time-zone: America/Bogota
    locale: es_CO